title: 岐阜県岐阜市
description: 岐阜県岐阜市内でテイクアウトできるお店情報
data_url: https://docs.google.com/spreadsheets/d/1ep_n84ukybjGiUpEFQX0qU8je71fzrjrS0w4LfFx-dQ/export?format=csv&gid=0
repository: https://github.com/Olein-jp/app/
form_url: https://docs.google.com/forms/d/e/1FAIpQLSf6VjLfcXbgdDnPForEwkIU0uqNkEP5NZDcSPiEnsns8nQccg/viewform
